// Code generated by protoc-gen-go.
// source: setserver/set.proto
// DO NOT EDIT!

/*
Package SetServer is a generated protocol buffer package.

It is generated from these files:
	setserver/set.proto

It has these top-level messages:
	Item
	Response
*/
package SetServer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Response_ResponseType int32

const (
	Response_SUCCESS Response_ResponseType = 0
	Response_ERROR   Response_ResponseType = 1
)

var Response_ResponseType_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
}
var Response_ResponseType_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
}

func (x Response_ResponseType) String() string {
	return proto.EnumName(Response_ResponseType_name, int32(x))
}
func (Response_ResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Item struct {
	Item string `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Type    Response_ResponseType `protobuf:"varint,1,opt,name=type,enum=SetServer.Response_ResponseType" json:"type,omitempty"`
	Present bool                  `protobuf:"varint,2,opt,name=present" json:"present,omitempty"`
	Error   string                `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Item)(nil), "SetServer.Item")
	proto.RegisterType((*Response)(nil), "SetServer.Response")
	proto.RegisterEnum("SetServer.Response_ResponseType", Response_ResponseType_name, Response_ResponseType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Set service

type SetClient interface {
	Add(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
	Contains(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
}

type setClient struct {
	cc *grpc.ClientConn
}

func NewSetClient(cc *grpc.ClientConn) SetClient {
	return &setClient{cc}
}

func (c *setClient) Add(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/SetServer.Set/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setClient) Remove(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/SetServer.Set/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setClient) Contains(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/SetServer.Set/Contains", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Set service

type SetServer interface {
	Add(context.Context, *Item) (*Response, error)
	Remove(context.Context, *Item) (*Response, error)
	Contains(context.Context, *Item) (*Response, error)
}

func RegisterSetServer(s *grpc.Server, srv SetServer) {
	s.RegisterService(&_Set_serviceDesc, srv)
}

func _Set_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SetServer).Add(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Set_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SetServer).Remove(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Set_Contains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SetServer).Contains(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Set_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SetServer.Set",
	HandlerType: (*SetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Set_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Set_Remove_Handler,
		},
		{
			MethodName: "Contains",
			Handler:    _Set_Contains_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4e, 0x2d, 0x29,
	0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x07, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0x83, 0x53, 0x4b, 0x82, 0xc1, 0x82, 0x4a, 0x22, 0x5c, 0x2c, 0x9e, 0x25, 0xa9, 0xb9, 0x42, 0x3c,
	0x5c, 0x2c, 0x99, 0x40, 0x5a, 0x82, 0x51, 0x81, 0x51, 0x83, 0x53, 0xa9, 0x89, 0x91, 0x8b, 0x23,
	0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8f, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x15,
	0x2c, 0xc5, 0x67, 0xa4, 0xa0, 0x07, 0xd7, 0xac, 0x07, 0x53, 0x02, 0x67, 0x84, 0x00, 0xd5, 0x09,
	0xf1, 0x73, 0xb1, 0x17, 0x14, 0xa5, 0x16, 0xa7, 0xe6, 0x95, 0x48, 0x30, 0x01, 0xb5, 0x70, 0x08,
	0xf1, 0x72, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49, 0x30, 0x83, 0x0d, 0x57, 0xe3, 0xe2, 0x41,
	0x51, 0xcf, 0xcd, 0xc5, 0x1e, 0x1c, 0xea, 0xec, 0xec, 0x1a, 0x1c, 0x2c, 0xc0, 0x20, 0xc4, 0xc9,
	0xc5, 0xea, 0x1a, 0x14, 0xe4, 0x1f, 0x24, 0xc0, 0x68, 0x34, 0x8b, 0x91, 0x8b, 0x19, 0x68, 0x97,
	0x90, 0x2e, 0x17, 0xb3, 0x63, 0x4a, 0x8a, 0x10, 0x3f, 0x92, 0xc5, 0x20, 0x27, 0x4b, 0x09, 0x63,
	0x71, 0x89, 0x12, 0x83, 0x90, 0x01, 0x17, 0x5b, 0x50, 0x6a, 0x6e, 0x7e, 0x59, 0x2a, 0xd1, 0x3a,
	0x8c, 0xb8, 0x38, 0x9c, 0xf3, 0xf3, 0x4a, 0x12, 0x33, 0xf3, 0x8a, 0x89, 0xd5, 0x93, 0xc4, 0x06,
	0x0e, 0x49, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x42, 0x7e, 0xdf, 0x60, 0x01, 0x00,
	0x00,
}
